<?php
/**
 * Created by PhpStorm.
 * User: rog
 * Date: 2020/6/30
 * Time: 17:21
 */
return [
    'id' => 'ID',
    'accountId' => '账号',
    'accountName' => '账户名',
    'password' => '密码',
    'starNO' => '游戏ID',
    'nickName' => '昵称',
    'level' => '等级',
    'phone' => '手机号',
    'headImg' => '头像',
    'customHeadImg' => '客户头像',
    'state' => '账号状态',
    'lockTime' => '冻结时间',
    'accountMoney' => '当前金币',
    'bankMoney' => '常规金库',
    'bankAccural' => '聚宝盆金币',
    'matchLockMoney' => '比赛冻结',
    'bankFixeMoney' => 'GM冻结',
    'selfLockMoney' => '自己冻结',
    'createTime' => '注册时间',
    'lastLoginTime' => '上次登录时间',
    'bankEndTime' => '金库到期时间',
    'mall_points' => '商城积分',
    'game_vip' => '游戏vip',
    'game_record' => '游戏记录',
    'encrypted_detail' => '密保详情',
    'accountType' => 'check',
    'matchMoney' => '赛事基金',
    'charitableMoney' => '商城积分',
    'gold' => '金币',
    'vip' => 'vip等级',
    'vaildTime' => '到期时间',
    'kickUsedNum' => '踢人次数',
    'gameStartTime' => '游戏开始时间',
    'gameEndTime' => '游戏结束时间',

    'registSource' => '注册来源',

    'totalBill' => '总流水',
    'jetton' => '筹码',
    'winLoseToday' => '今日输赢',
    'recommended' => '推荐人',
    'scoreBeforeGame' => '游戏开始前分数',
    'scoreAfterGame' => '游戏结束后分数',
    'scoreBet' => '下注分数',
    'scoreWin' => '赢取分数',
    'scoreLose' => '输掉分数',

    'accountPassword' => '账户密码',
    'age' => '年龄',
    'customImgUrl' => '图片',
    'exp' => 'Exp',
    'expCalculateTime' => '游戏时间',
    'logoutTime' => '登出时间',
    'robotFlag' => '重启标识',
    'serviceGameId' => '服务游戏id',
    'sex' => '性别',
    'sign' => '个性签名',
    'track' => 'Track',
    'matchID' => 'MatchID',


    'playId' => '明星号',
    'winOrlose' => '输赢金币',
    'time' => '时间',
    'multiple' => '倍数',
    'gameId' => '游戏ID',
    'type' => '类型',
    "carryMoney" => '携带金币',
    'cornucopiaMoney' => '聚宝盆金币',
    'operateMoney' => '操作金币',
    'vaultMoney' => '金库金币',
    'buyMoney' => '购买金额',
    'buyTime' => '购买时间',
    'faceValue' => '彩票面额',
    'winMoney' => '输赢金额',
    'valueRecord' => '彩票记录',
    'gameRecord' => '游戏记录',
    'bankRecord' => '金库记录',
    'regSource' => '注册来源',
    'gameName' => '游戏名称',
    'wLSocreToday' => '玩家今日输赢总分',
    'wLScore' => '玩家输赢总分',
    'leftGold' => '当前剩余金币',
    'leftGold2' => '剩余金币',
    'loginTime' => '上次登录时间',
    'gameTime' => '游戏时间',
    'jettonBeforeGame' => '游戏前筹码',
    'jettonAfterGame' => '游戏后筹码',
    'amountOfPoints' => '上分数额',


    'changeMoney' => '变化金币',
    'nowMoney' => '变化后金币',
    'oldMoney' => '变化前金币',
    'sourceReason' => '变化原因',
    'changeReason' => '变化原因',
    'startTimes' => '开始时间',
    'endTimes' => '结束时间',
    'createStartTime' => '注册开始时间',
    'createEndTime' => '注册结束时间',


    'serverId' => '服务器标识',
    'serverName' => '服务器名称',
    'inventoryAttenuation' => '库存衰减率',
    'smallStock' => '小库存',
    'mediumStock' => '中库存',
    'largeStock' => '大库存',
    'extraLargeStock' => '特大库存',
    'adjustFundAmount' => '调节基金总额',
    'recoveryToday' => '今日回收率',
    'revenueToday' => '今日税收',
    'stockId' => '库存ID',
    'stockDesc' => '库存描述',
    'difficultId' => '难度ID',
    'difficultDesc' => '难度描述',
    'stockScore' => '库存分数',
    'jump' => '跳转几率',
    'prizePoolGrowthRate' => '奖池增长率',
    'smallJackpotScore' => '小奖池真实分数',
    'mediumJackpotScore' => '中奖池真实分数',
    'largeJackpotScore' => '大奖池真实分数',
    'smallestIncrease' => '最小增减',
    'normalIncrease' => '普通增减',
    'maximumIncrease' => '最大增减',
    'inventoryDecayRate' => '库存衰减率',
    'small' => '小',
    'medium' => '中',
    'large' => '大',
    'extraLarge' => '特大',
    'phaseNum' => '阶段编号',
    'desc' => '描述',
    'riskFree' => '免费几率',
    'freeMinimumMultiple' => '免费最小倍数',
    'freeMaximumMultiple' => '免费最大倍数',
    'odds1' => '几率1',
    'minimumMultiple1' => '最小倍数1',
    'maxinumMultiple2' => '最大倍数1',
    'odds2' => '几率2',
    'minimumMultiple2' => '最小倍数2',
    'smallJackpotScoreS' => '小奖池中奖阶段分数',
    'mediumJackpotScoreS' => '中奖池中奖阶段分数',
    'largeJackpotScoreS' => '大奖池中奖阶段分数',
    'smallJackpotOdds' => '小奖池中奖几率',
    'mediumJackpotOdds' => '中奖池中奖几率',
    'largeJackpotOdds' => '大奖池中奖几率',
    'smallJackpotRatio' => '小奖池中奖比例',
    'mediumJackpotRatio' => '小奖池中奖比例',
    'largeJackpotRatio' => '小奖池中奖比例',
    'thresholdValue' => '阈值',
    'control_inventory' => '控制库存',
    'change_inventory' => '更改库存',
    'winLoseValue' => '点控输赢值',
    'totalBet' => '总投注值',
    'totalWinLose' => '总输赢',
    'changeValue' => '改变值',
    'is_enable' => '是否启用',
    'frequencyRange' => '次数范围上限',
    'rechargeLimit' => '充值额度',
    'winTriggerProportion' => '赢限制触发比例',
    'winTargetProportion' => '赢目标比例',
    'loseTriggerProportion' => '输触发限制比例',
    'loseTargetProportion' => '输目标比例',
    'totalTimes' => '调控总次数',
    'loseDifficultIndex' => '输配置难度索引',
    'winDifficultIndex' => '赢配置难度索引',
    'controlId' => '调控id',
    'rechargeAmount' => '充值金额',
    'triggerControlAmount' => '触发调控金额(低)',
    'endAdjustAmount' => '结束调控金额(低)',
    'triggerControlAmount2' => '触发调控金额(高)',
    'endAdjustAmount2' => '结束调控金额(高)',
    'remainingControlTimes' => '剩余有效调控次数',
    'stateTrigger' => '触发状态',
    'regulationOfLose' => '调控输',
    'regulationOfWin' => '调控赢',
    'is_complete' => '是否完成',
    'title' => '公共标题',
    'content' => '公共内容',
    'publicPlatform' => '公共发布平台（H5或APP）',
    'startTime' => '公共开始时间',
    'endTime' => '公共结束时间',
    'intervalTime' => '发布公共时间间隔（秒）',
    'publicType' => '公共类型',
    'optimizePriority' => '公告优先级',
    'uploadImg' => '上传图片',
    'inputContent' => '输入公告类型',
    'recharge' => '充值',
    'withdraw' => '提现',
    'rechargeSusidy' => '充值补助',
    'firstRechargeSusidy' => '首充补助',
    'commisionIssued' => '佣金发放',
    'commisionExtract' => '佣金提取',
    'reliefFund' => '救济金',
    'betOn' => '押注',
    'sendPrize' => '派奖',
    'inventory' => '库存',
    'bindGold' => '绑定金币',
    'unBindGold' => '非绑定金币',
    'date' => '日期',
    'betNumber' => '玩家投注人数',
    'betGold' => '玩家投注金额',
    'obtainGold' => '玩家获得金币',
    'profitAmount' => '系统总盈利',
    'ranking' => '名次',


    'apply_time' => '开始报名时间',
    'end_time' => '截止时间',
    'game_id' => '游戏ID',
    'apply_cost' => '报名费',
    'open_num' => '开启次数',
    'differ_hour' => '间隔时间',
    'award' => '奖励',
    'charge' => '手续费',


    'totalWin' => '累计下注',
    'totalLose' => '累计输钱',
    'serialization' => '序列化',
    'emailPublishPlatform' => '邮件发布平台',
    'receiver' => '收件人',

    'vipGrade' => 'VIP等级',
    'totalCommission' => '累计获得佣金',
    'commissionReceived' => '已领取佣金',
    'commissionPayable' => '可提取佣金',
    'personalPerformanceWeek' => '本周个人业绩',
    'teamPerformanceWeek' => '本周团队业绩',
    'superiorId' => '上级ID',
    'directlyNum' => '直属人数',
    'teamNum' => '团队人数',
    'registerTime' => '注册时间',

    'commissionId' => '推广ID',
    'vipGarde' => 'VIP等级',
    'getCommission' => '获得佣金',
    'createdAt' => '创建时间',
    'turnOutCommission' => '转出佣金',
    'orderId' => '订单号',

    'leftCommission' => '转后剩余',
    'status' => '状态',
    'getTime' => '领取时间',


    'upperLimit' => '上限',
    'lowerLimit' => '下限',
    'rebate' => '万/返佣',

    'beginTime' => '开始时间',
    'endTime2' => '结束时间',
    'gameRounds' => '比赛轮次',
    'distributionGold' => '发放金币',
    'awardsNum' => '奖项数量',
    'playDetail' => '比赛详情',
    'eventDetail' => '赛事详情',

    'agentRole' => '代理账号角色',
    'associatedGameAccount' => '关联游戏账号',
    'associatedGameId' => '关联游戏ID',
    'agencyCommission' => '代理佣金(不超3%)',
    'platFormWinLose' => '平台输赢',
    'platformFee' => '平台费',
    'inverse' => '反水',
    'discount' => '优惠',

    'totalRegister' => '总注册人数',
    'increasedToday' => '当日新增人数',
    'totalRecharge' => '总充值金额',
    'rechargeToday' => '当日充值金额',
    'totalRechargeNum' => '总充值数',
    'rechargeNumToday' => '当日新增充值数',
    'activeUserToday' => '当日活跃用户',
    'totalWinLoseRatio' => '总输赢比',
    'winLoseRatioToday' => '当日输赢比',
    'firstDownloadNum' => '当日下载',
    'nextDayLogin' => '次日登录',
    'threeDaysLogin' => '三日登录',
    'fourDaysLogin' => '四日登录',
    'fiveDaysLogin' => '五日登录',
    'sixDaysLogin' => '六日登录',
    'sevenDaysLogin' => '七日登录',

    'rechargeNum' => '充值数量',
    'rechargeAt' => '充值时间',


    'orderNo' => '订单号',

    'rechargeWay' => '充值渠道',
    'rechargeTime' => '发起充值时间',
    'rechargeSource' => '充值来源',
    'rechargeStatus' => '充值状态',
    'rechargeSubsidy' => '充值补助',
    'payWay' => '支付渠道',
    'orderStatus' => '订单状态',
    'orderDesc' => '订单描述',
    'orderTime' => '订单时间',
    'orderCompleteTime' => '完成时间',

    'withdrawalAmount' => '提现金额',
    'accountChannel' => '渠道账号',
    'withdrawalChannel' => '提现渠道',
    'source' => '来源',
    'applyTime' => '申请时间',


    'withdrawAmount' => '提现金额',
    'levyProportion' => '抽税比例',
    'taxCredits' => '计税额度',
    'tax' => '本次税款',
    'freeTaxWithdraw' => '提现前剩余免税金额',
    'freeTaxAfterWithdraw' => '提现后剩余金额',

    'totalWithdraw' => '当前累计提现金额',
    'curWithdraw' => '本次累计提现金额',

    'withdrawChannel' => '提现渠道',

    'completeTime' => '完成时间',

    'money' => '金币',
    'aesKey' => 'aesKey',
    'agentId' => '代理id',
    'md5Key' => 'md5Key',


];